YO YO YO GOOOD COURSE I G BUT I GOT NO TIME TO SPARE

In [67]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [68]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [69]:
## introduction to TENSORS (tensors are crazy)
## creating tensors
# pytorch tensors are created using pytorch.tensors

In [70]:
import torch
#scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [71]:
scaler.ndim

0

In [72]:
#get tensor back as python int
scaler.item()

7

In [73]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [74]:
# dimesnions = numebr of square brackets closing ones
vector.ndim

1

In [75]:
#no of elements in the closing square brackets
vector.shape

torch.Size([2])

In [76]:
matrix=torch.tensor([[7,10],[9,8]])
matrix

tensor([[ 7, 10],
        [ 9,  8]])

In [77]:
matrix.shape

torch.Size([2, 2])

In [78]:
matrix.ndim

2

In [79]:
matrix.size()

torch.Size([2, 2])

In [80]:
matrix[1]

tensor([9, 8])

In [81]:
import torch
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[3,4,5]],[[1,2,3],[4,5,9],[3,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [3, 4, 5]],

        [[1, 2, 3],
         [4, 5, 9],
         [3, 4, 5]]])

In [82]:
TENSOR.ndim

3

In [83]:
TENSOR.size()


torch.Size([2, 3, 3])

In [84]:
TENSOR[0][1]

tensor([3, 6, 9])

#RANDOM TESNORS

# Random tensors are imp because the way many nn learn is that they start with
# full of random num and then they adjust those random numbers to better represent the data


In [85]:
#creating a random tensor of size (3,4) it means that it has two arrays with 3 and 4 elements in them
random_tensor=torch.rand(3,4) #3 rows and 4 cols ok
random_tensor
random_tensor= torch.rand(3,3,4) #generate 3 with 3 rows and 4 cols
random_tensor

tensor([[[0.5666, 0.2514, 0.0469, 0.6972],
         [0.7101, 0.5204, 0.3667, 0.6112],
         [0.9603, 0.4308, 0.8906, 0.9162]],

        [[0.6907, 0.8230, 0.4408, 0.1226],
         [0.4802, 0.5000, 0.6456, 0.0628],
         [0.5306, 0.6931, 0.5445, 0.1422]],

        [[0.4287, 0.1334, 0.4317, 0.4421],
         [0.4669, 0.9675, 0.5011, 0.5819],
         [0.7917, 0.7000, 0.0889, 0.7781]]])

In [86]:
random_image_tensor=torch.rand(size=(224,224,3)) #height width colour channels (R,G,B)
random_image_tensor.shape , random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [87]:
# TENSORS with 0s and 1s ok easy easy
zero=torch.zeros(size=(3,4))
zero
ones= torch.ones((3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [88]:
ones.dtype

torch.float32

In [89]:
type(zero)

torch.Tensor

#creating range of tensors

In [90]:
one_to_ten=torch.arange(1,11) # instead of range
one_to_ten
stepping_stones=torch.arange(0,100,0.9)
stepping_stones

tensor([ 0.0000,  0.9000,  1.8000,  2.7000,  3.6000,  4.5000,  5.4000,  6.3000,
         7.2000,  8.1000,  9.0000,  9.9000, 10.8000, 11.7000, 12.6000, 13.5000,
        14.4000, 15.3000, 16.2000, 17.1000, 18.0000, 18.9000, 19.8000, 20.7000,
        21.6000, 22.5000, 23.4000, 24.3000, 25.2000, 26.1000, 27.0000, 27.9000,
        28.8000, 29.7000, 30.6000, 31.5000, 32.4000, 33.3000, 34.2000, 35.1000,
        36.0000, 36.9000, 37.8000, 38.7000, 39.6000, 40.5000, 41.4000, 42.3000,
        43.2000, 44.1000, 45.0000, 45.9000, 46.8000, 47.7000, 48.6000, 49.5000,
        50.4000, 51.3000, 52.2000, 53.1000, 54.0000, 54.9000, 55.8000, 56.7000,
        57.6000, 58.5000, 59.4000, 60.3000, 61.2000, 62.1000, 63.0000, 63.9000,
        64.8000, 65.7000, 66.6000, 67.5000, 68.4000, 69.3000, 70.2000, 71.1000,
        72.0000, 72.9000, 73.8000, 74.7000, 75.6000, 76.5000, 77.4000, 78.3000,
        79.2000, 80.1000, 81.0000, 81.9000, 82.8000, 83.7000, 84.6000, 85.5000,
        86.4000, 87.3000, 88.2000, 89.10

In [91]:
#creating tensors like
ten_zeroes= torch.zeros_like(input=one_to_ten)
ten_zeroes= torch.zeros(10,dtype=int)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATATYPES


In [92]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor.dtype # even though i said none still float32


torch.float32

``` TENSORS ARE ONE OF THE 3 BIG ERRORS 1. TENSORS NOT RIGHT DATATYPE2. TENSORS NOT RIGHT SHAPE```3. TENSORS NOT ON THE RIGHT DEVICE```

In [93]:
some_tensor= torch.rand(3,4)
some_tensor

tensor([[0.0956, 0.2915, 0.3749, 0.3224],
        [0.6958, 0.5683, 0.1567, 0.8442],
        [0.1989, 0.4262, 0.5866, 0.2557]])

``` finding details about the tensor```

In [94]:
some_tensor.shape


torch.Size([3, 4])

In [95]:
print(some_tensor.dtype)
print(some_tensor.device)
print(some_tensor.ndim)

torch.float32
cpu
2


```tensor operation```

In [96]:
#add,mul sub,divide, matrix mul ,

In [97]:
tensor=torch.tensor([1,2,3],dtype=int)
tensor+=10
tensor

tensor([11, 12, 13])

``` element wise multiplication and matrix multiplilcation ```

In [98]:
tensor*tensor


tensor([121, 144, 169])

In [99]:
#Matrix multipliation
torch.matmul(tensor,tensor)

tensor(434)

In [100]:
mat1=torch.rand(3,5)
mat2=torch.rand(5,3)
torch.mm(mat1,mat2)
mat2.T.shape

torch.Size([3, 5])

``` time for learning tensor aggregation```

In [101]:
x= torch.arange(1,10)
print(x)
torch.max(x) ,x.max()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


(tensor(9), tensor(9))

In [102]:
# x.mean() #error
x.type(torch.float32).mean()
x.sum()
torch.sum(x)

tensor(45)

positional min and max means finding the min and max index argmin and argmax

In [103]:
torch.argmin(x) , torch.argmax(x)

(tensor(0), tensor(8))

``` RESHAPING , STACKING , SQUEEZING AND UNSQEEZING```

In [104]:
# Stacking torch.vstack,torch.hstack for merging stacking tensors
# view return a view of an input tensor of certain shape but keep the same
#memory as the original tensor

```squeeze removes all `1` Dimsension from tensor
torch.unsqueeze add 1 d to target tensor
permute return a view of the input with dimensions permuted (swapped) in a certain way```

In [105]:
import torch
x= torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [106]:
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [107]:
z=x.view(1,9)
z,z.shape
# x and z share same memeory so change in z wll reflect change in x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [108]:
# stackng time
x_stacked=torch.stack([x,x,x,x,x,x,x])
x_hstacked=torch.hstack([x,x,x,x])
x_stacked,x_hstacked

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
         1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [109]:
# time to squeeze
x= torch.zeros(2,1,2,1)
x_squeezed=x.squeeze()
x_squeezed #only 2,2 shape left
# it removes all 1 d's

tensor([[0., 0.],
        [0., 0.]])

In [110]:
# time to unsqueeze adds a single dim to target tensor at required place well
x_unsqueezed=x_squeezed.unsqueeze(dim=2)
x_unsqueezed.shape

torch.Size([2, 2, 1])

In [111]:
torch.permute(x_unsqueezed,(1,0,2))
# used with images well
x_original=torch.rand(size=(224,224,3)) #height width color_channels
x_permuted=x_original.permute(2,0,1) # shifts axis
print(x_original.shape)
print(x_permuted.shape)
# a view shares same memory with the original so changes will be visible both sides
#return a view of the oriinal input with its dimensions permuted

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [112]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [113]:
a= torch.rand(1,2,3,4,5)
a,a.ndim
a[0 ,1,2,2,2]
a=torch.arange(1,10)
a=a.reshape(1,3,3)
a[:,:,2]

tensor([[3, 6, 9]])

# ndarray to tensor torch.from_numpy(ndarray)
#

In [114]:
import numpy as np
import torch
array= np.arange(1,11)
tensor=torch.from_numpy(array)
array,tensor


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

``` PYTORCH REPRODUCABILITY```

In [115]:
import torch
random_tensor_A= torch.rand(2,3)
random_tensor_B= torch.rand(2,3)
print(random_tensor_A,random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.6970, 0.9616, 0.8041],
        [0.1131, 0.1240, 0.8493]]) tensor([[0.2068, 0.0994, 0.9841],
        [0.5655, 0.7632, 0.9146]])
tensor([[False, False, False],
        [False, False, False]])


In [116]:
# lets make tensors reproducable
random_seed=33
torch.manual_seed(random_seed)
random_tensor_C= torch.rand(2,3)
torch.manual_seed(random_seed) # only work for one block of code for clab here
random_tensor_D=torch.rand(2,3)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)


tensor([[0.6186, 0.5587, 0.1937],
        [0.3360, 0.2008, 0.6970]])
tensor([[0.6186, 0.5587, 0.1937],
        [0.3360, 0.2008, 0.6970]])
tensor([[True, True, True],
        [True, True, True]])


In [117]:
torch.cuda.is_available()


False

In [118]:
# device agnostic code
device= "cuda" if torch.cuda.is_available() else "cpu"


``` pytorch can run on both cpu and gpu and that is super great so it is necessary to write device agnostic code```

In [119]:
tensor=torch.tensor([1,2,3]) #default on cpu
tensor.device
tensor.device

device(type='cpu')